#!/usr/bin/env node

/**
 * BTNG Genesis Transaction Recorder
 * Captures and logs the first real BTNG transaction
 */

const fs = require('fs');
const path = require('path');

function recordGenesisTransaction(txDetails) {
  const logPath = path.join(__dirname, '..', 'BTNG_GENESIS_TX_LOG.md');

  // Read current log
  let logContent = fs.readFileSync(logPath, 'utf8');

  // Update the transaction details
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];
  const timeStr = now.toTimeString().split(' ')[0];

  logContent = logContent
    .replace('- **Date:** February 18, 2026', `- **Date:** ${dateStr}`)
    .replace('- **Time:** [To be recorded at broadcast]', `- **Time:** ${timeStr}`)
    .replace('- **Sender Address:** [Generated by demo wallet]', `- **Sender Address:** ${txDetails.senderAddress}`)
    .replace('- **Receiver Address:** [Test recipient address]', `- **Receiver Address:** ${txDetails.receiverAddress}`)
    .replace('- **Amount:** 1.000000 BTNG', `- **Amount:** ${txDetails.amount} BTNG`)
    .replace('- **Fee:** 0.001000 BTNG', `- **Fee:** ${txDetails.fee} BTNG`)
    .replace('- **Transaction Hash:** [0x + 64-character hash from backend]', `- **Transaction Hash:** ${txDetails.txHash}`)
    .replace('- **Block Height:** [Current height + 1]', `- **Block Height:** ${txDetails.blockHeight}`)
    .replace('- **Timestamp:** [Unix timestamp from backend]', `- **Timestamp:** ${txDetails.timestamp}`)
    .replace('http://74.118.126.72:64799/explorer/tx/[hash]', `http://74.118.126.72:64799/explorer/tx/${txDetails.txHash}`)
    .replace('- [ ] Wallet balance updated (-1.001 BTNG)', '- [x] Wallet balance updated (-1.001 BTNG)')
    .replace('**Current Status:** Awaiting BTNG backend activation', '**Current Status:** ✅ GENESIS TRANSACTION RECORDED')
    .replace('**Next Steps:**', '**Genesis Transaction Completed:**');

  // Add confirmation notes
  const confirmationNotes = `

## ✅ CONFIRMATION LOG
**Transaction Broadcast:** ${dateStr} ${timeStr}
**Backend Response:** ${JSON.stringify(txDetails.backendResponse, null, 2)}

**Verification Steps Completed:**
- ✅ Transaction submitted to backend
- ✅ Response received with transaction hash
- ✅ Genesis log updated with real data
- ⏳ Awaiting block confirmation (monitor explorer)

**Sovereign Milestone Achieved:** First economic transaction on BTNG network
`;

  logContent += confirmationNotes;

  // Write updated log
  fs.writeFileSync(logPath, logContent);

  console.log('🎉 GENESIS TRANSACTION RECORDED!');
  console.log('================================');
  console.log(`Date: ${dateStr}`);
  console.log(`Time: ${timeStr}`);
  console.log(`Hash: ${txDetails.txHash}`);
  console.log(`Amount: ${txDetails.amount} BTNG`);
  console.log('');
  console.log('✅ BTNG Sovereign Network is now ACTIVE!');
  console.log('📄 Full details saved to BTNG_GENESIS_TX_LOG.md');

  return {
    success: true,
    logPath: logPath,
    transaction: txDetails
  };
}

// Example usage (when backend is ready):
/*
recordGenesisTransaction({
  senderAddress: 'BTNG1ABC123...',
  receiverAddress: 'BTNG1XYZ789...',
  amount: '1.000000',
  fee: '0.001000',
  txHash: '0x1234567890abcdef...',
  blockHeight: 12458,
  timestamp: 1708272000,
  backendResponse: { success: true, txHash: '0x...' }
});
*/

module.exports = { recordGenesisTransaction };

// CLI usage
if (require.main === module) {
  // For testing - create a mock genesis transaction
  const mockTx = {
    senderAddress: 'BTNG1DEMO123456789012345678901234567890',
    receiverAddress: 'BTNG1GENESIS123456789012345678901234567890',
    amount: '1.000000',
    fee: '0.001000',
    txHash: '0x' + '1'.repeat(64),
    blockHeight: 12458,
    timestamp: Math.floor(Date.now() / 1000),
    backendResponse: {
      success: true,
      txHash: '0x' + '1'.repeat(64),
      message: 'Genesis transaction broadcast successfully'
    }
  };

  console.log('🚀 Recording BTNG Genesis Transaction...');
  recordGenesisTransaction(mockTx);
}